api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    graphql:
        graphiql:
            enabled: true # default route is /graphql
        graphql_playground:
            enabled: false # default route is /graphql/graphql_playground
