doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            geography: Jsor\Doctrine\PostGIS\Types\GeographyType
            geometry: Jsor\Doctrine\PostGIS\Types\GeometryType
            raster: Jsor\Doctrine\PostGIS\Types\RasterType
            jsonb: Boldtrn\JsonbBundle\Types\JsonbArrayType
        mapping_types:
            jsonb: jsonb

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                JSONB_AG:    Boldtrn\JsonbBundle\Query\JsonbAtGreater
                JSONB_HGG:   Boldtrn\JsonbBundle\Query\JsonbHashGreaterGreater
                JSONB_EX:    Boldtrn\JsonbBundle\Query\JsonbExistence
                ST_Distance: Jsor\Doctrine\PostGIS\Functions\ST_Distance
                ST_Point:    Jsor\Doctrine\PostGIS\Functions\ST_Point
